version: "3.8"

services:
  backend:
    build: .
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
